### ISSUE TITLE
Looks Ugly with RequestPolicy

### ISSUE THREAD

**Issue by paragonie-scott** [php-fig/php-fig.github.com#167]
1. Install RequestPolicy for Firefox.
2. Visit the website.
3. See this:

![phpfig](https://cloud.githubusercontent.com/assets/11591518/10766121/5d36fcd2-7cac-11e5-9da7-959d6f5309ba.png)

Solution: Host the fonts instead of having typography.com host them.

**Comment by reinink** [comment]
Hmm, yeah, without the fonts the site looks awful. I think we need some more sensible fallbacks, which will help a lot. Adding this to my list.

As for self hosting, I'm not sure that's possible, since Hoefler & Co fonts are very difficult to get web versions of, in fact typography.com my be the only way.

**Comment by paragonie-scott** [comment]
Can't you just download them/their CSS files from typography.com and commit them to the repository?

**Comment by reinink** [comment]
@paragonie-scott I don't think so, but I'll definitely look into it. Have you done this with typography.com  before?

**Comment by paragonie-scott** [comment]
I did it with Google Web Fonts.

**Comment by reinink** [comment]
Yeah, but that's a free service. ;)

**Comment by paragonie-scott** [comment]
http://php-fig.reinink.ca/fonts/381826/4B759EF1658620CE5.css

I dunno, it looks pretty easy to copy onto your own server.

**Comment by simensen** [comment]
Just because you can copy the files (easily or otherwise) it does not mean you are authorized to do so. Licensing and all that. Don't just blindly copy fonts or other assets without making sure you should. Some licenses on these font services are free and licensed only for use via the CDN/font service itself.

**Comment by paragonie-scott** [comment]
> Just because you can copy the files (easily or otherwise) it does not mean you are authorized to do so.

Of course.

> Some licenses on these font services are free and licensed only for use via the CDN/font service itself.

If you're paying to use the service, can't you negotiate with them? I mean, this isn't really a big deal either way. I use RequestPolicy to stop a wide swath of watering hole attacks, and normally it doesn't fail to report that it's blocking something. I don't think most Internet users care enough about their security to put up with that inconvenience.

**Comment by dragoonis** [comment]
Will google web fonts help here? We would degrade to some standard fonts to keep the site a bit more in check.

**Comment by paragonie-scott** [comment]
Well, the issue I experienced is that the default fonts are sized differently, which caused the buttons to resize and get bumped down. If there was some way to detect that the font face isn't loaded and change the font size to correspond to it, that'd be awesome.

**Comment by paragonie-scott** [comment]
This has been fixed for an undetermined period of time. At least, I don't encounter it anymore, and that's good enough.
