### ISSUE TITLE
suggest: use HTTPS

### ISSUE THREAD

**Issue by sinkcup** [php-fig/php-fig.github.com#225]
Now is 2017, many sites have using HTTPS, even "force HTTPS"(redirect HTTP to HTTPS).

As a tech website, [php-fig.org](https://www.php-fig.org) don't support HTTPS, it's so sad...

I suggest php-fig use HTTPS.

docs:

- [Why HTTPS Matters | Web | Google Developers](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https)
- [Let’s Encrypt is a free, automated, and open Certificate Authority.](https://letsencrypt.org/)

**Comment by reinink** [comment]
The issue here is that the site is hosted on GitHub Pages, and there is [no support for HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/):

> HTTPS is not supported for GitHub Pages using custom domains.

That said, this is easily enough done if you use Cloudflare, which offers free HTTPS. That's what we do on The PHP League sites. For example: https://thephpleague.com/

This, however, would require a change in DNS hosts, which may not be preferred. I'll let @michaelcullum speak to that.

**Comment by sinkcup** [comment]
Yes, using CDN HTTPS is a good choice, changing DNS is not hard, waiting for @michaelcullum

**Comment by stefanotorresi** [comment]
done in #230
